---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: rhel6
    image: centos:6
  - name: rhel7
    image: centos:7
  - name: suse
    image: darksheer/sles11sp4
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
